{"name": "test_wallet_spend_cash_raises_exception_on_insufficient_amount", "status": "passed", "start": 1623009174490, "stop": 1623009174490, "uuid": "230d39c1-22e5-453e-8b0d-2b0856ff803d", "historyId": "55955f8eb56589d497fd690a9579b01e", "testCaseId": "f9b84f17daea404e6e8b8e24ee067106", "fullName": "PyTest.test_wallet_fixture#test_wallet_spend_cash_raises_exception_on_insufficient_amount", "labels": [{"name": "parentSuite", "value": "PyTest"}, {"name": "suite", "value": "test_wallet_fixture"}, {"name": "host", "value": "Sanjay-PC"}, {"name": "thread", "value": "3224-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "PyTest.test_wallet_fixture"}]}