{"name": "test_wallet_spend_cash_raises_exception_on_insufficient_amount", "status": "passed", "start": 1623009264287, "stop": 1623009264287, "uuid": "dbc40e09-495c-4e1e-9395-1291a7278087", "historyId": "041035d216191b67008c688c3ef5db87", "testCaseId": "fe8bdbc23ce8dc583d49819c41e3a066", "fullName": "PyTest.test_wallet#test_wallet_spend_cash_raises_exception_on_insufficient_amount", "labels": [{"name": "parentSuite", "value": "PyTest"}, {"name": "suite", "value": "test_wallet"}, {"name": "host", "value": "Sanjay-PC"}, {"name": "thread", "value": "3200-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "PyTest.test_wallet"}]}