{"name": "test_comparewithCC_file2", "status": "failed", "statusDetails": {"message": "AssertionError: cc and zz comparison failed\nassert 45 == 25", "trace": "supply_AA_BB_CC = [25, 35, 45]\n\n    def test_comparewithCC_file2(supply_AA_BB_CC):\n    \tzz=25\n>   \tassert supply_AA_BB_CC[2]==zz,\"cc and zz comparison failed\"\nE    AssertionError: cc and zz comparison failed\nE    assert 45 == 25\n\nPyTest\\test_basic_fixture2.py:12: AssertionError"}, "start": 1623009347424, "stop": 1623009347424, "uuid": "02c310b3-3269-44b5-9ad3-fdc6a306fe84", "historyId": "94d421f6fc21906bcb76ce5cff3318ef", "testCaseId": "a59f0f1f266a23a736fd874f80a9e443", "fullName": "PyTest.test_basic_fixture2#test_comparewithCC_file2", "labels": [{"name": "parentSuite", "value": "PyTest"}, {"name": "suite", "value": "test_basic_fixture2"}, {"name": "host", "value": "Sanjay-PC"}, {"name": "thread", "value": "108-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "PyTest.test_basic_fixture2"}]}