{"name": "test_wallet_spend_cash_raises_exception_on_insufficient_amount", "status": "passed", "start": 1623009347705, "stop": 1623009347705, "uuid": "ffaac6af-583a-4d5b-b448-332ff334a3fd", "historyId": "55955f8eb56589d497fd690a9579b01e", "testCaseId": "f9b84f17daea404e6e8b8e24ee067106", "fullName": "PyTest.test_wallet_fixture#test_wallet_spend_cash_raises_exception_on_insufficient_amount", "labels": [{"name": "parentSuite", "value": "PyTest"}, {"name": "suite", "value": "test_wallet_fixture"}, {"name": "host", "value": "Sanjay-PC"}, {"name": "thread", "value": "108-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "PyTest.test_wallet_fixture"}]}